import ZeroGradientLean.Geometry
import ZeroGradientLean.Argyris
import ZeroGradientLean.TraceP3
import ZeroGradientLean.Nitsche
import ZeroGradientLean.MainTheorem
import ZeroGradientLean.SharpConstants
import ZeroGradientLean.PressureWitness
namespace ZeroGradientLean
theorem selected_core_inventory_anchor : True := by trivial
#print axioms ZeroGradientLean.three_halves_pow_four
#print axioms ZeroGradientLean.argyris_cf_sq_identity
#print axioms ZeroGradientLean.trace_spectrum_bound
#print axioms ZeroGradientLean.nitsche_two_by_two_lower
#print axioms ZeroGradientLean.no_universal_h32_rate_at_small_scale
#print axioms ZeroGradientLean.residualSharp_below_exact_formula
#print axioms ZeroGradientLean.nitsche_continuity_sharp
#print axioms ZeroGradientLean.sharp_residual_forces_velocity
#print axioms ZeroGradientLean.sharp_no_universal_h32_rate
#print axioms ZeroGradientLean.beta_integral_exact
#print axioms ZeroGradientLean.beta_sq_integral_exact
#print axioms ZeroGradientLean.local_pressure_moment_factor_21
end ZeroGradientLean
